version: '3.7'

services:
  database_rentx:
    image: postgres
    container_name: database_battery
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=battery123
      - POSTGRES_DB=battery_store
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: battery_store
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database_battery
    depends_on:
      - database_battery

volumes:
  pgdata:
    driver: local
